[package]
name = "sare-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sare-core = { path = "../sare-core" }
secrecy = "0.8.0"
