[package]
name = "cryptopia-seed"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mnemonic = "1.0.1"
ring = "0.17.5"
sha3 = "0.10.8"
tiny-bip39 = "1.0.0"
cryptopia-kdf = {path = "../cryptopia-kdf"}
