[package]
name = "cryptopia-sign"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519-compact = "2.0.4"
cryptopia-seed = {path="../cryptopia-seed"}

[dev-dependencies]
base64 = "0.21.5"

